title: BizzNist
description: IT, websites, SEO, and growth — by Reema Roy.
baseurl: "" # root domain
url: "https://www.bizznist.com"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Posts setup
collections:
  posts:
    output: true
    permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
