title: BizzNist Blog
description: IT, websites, SEO, and growth — by Reema Roy.
url: "https://www.bizznist.com"
baseurl: ""   # keep empty, since Netlify deploys at root

permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Posts collection (custom path)
collections:
  posts:
    output: true
    permalink: /blog/:title/
    source: blog/_posts


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
