title: BizzNist Blog
description: IT, websites, SEO, and growth — by Reema Roy.
url: "https://www.bizznist.com"
baseurl: ""

permalink: /blog/:slug/

collections:
  posts:
    output: true
    permalink: /blog/:slug/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "blog/_posts"
      type: posts
    values:
      layout: post

paginate: 10
paginate_path: "/blog/page:num/"


url: "https://www.bizznist.com"   
baseurl: ""                  
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
