title: BizzNist Blog
description: IT, websites, SEO, and growth — by Reema Roy.
url: "https://www.bizznist.com"
baseurl: ""   # keep empty since Netlify deploys at root

collections:
  posts:
    output: true
    permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
