title: BizzNist Blog
description: IT, websites, SEO, and growth — by Reema Roy.
baseurl: "/blog"
url: "https://www.bizznist.com"


# Build settings
markdown: kramdown
permalink: "/blog/:title/"


# Plugins
plugins:
- jekyll-seo-tag
- jekyll-sitemap


# Collections & defaults
collections:
posts:
output: true
permalink: "/blog/:title/"


# Defaults for posts
defaults:
- scope:
path: ""
type: "posts"
values:
layout: post
is_post: true


# Where images uploaded via CMS go
uploads_dir: assets/uploads
