backend:
  name: git-gateway
  branch: main   # or the branch your site deploys from

site_url: https://bizznist-blogs.netlify.app
display_url: https://bizznist-blogs.netlify.app

media_folder: "assets/uploads"   # where images get stored in your repo
public_folder: "/assets/uploads" # how images are referenced on the site

publish_mode: simple

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"   # make sure this matches your repo
    create: true
    extension: "md"
    slug: "{{slug}}"   # CMS will auto-generate from Title, but we’ll also add a custom field
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Custom URL Slug", name: "custom_slug", widget: "string", required: false, hint: "Leave empty to auto-generate" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Reema Roy" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "richtext" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "Meta Keywords", name: "meta_keywords", widget: "list", required: false }
      
